services:
  firebase:
    container_name: firebase
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Used by entrypoint
      - DATA_DIR=/app/mnt/data
      - FIREBASE_DIR=/app/services/firebase
    volumes:
      - db:/app/mnt/data
      - ./entrypoint:/usr/local/bin/entrypoint
      - ./firebase:/app/services/firebase
      # Ignoring local node_modules
      - /app/services/firebase/functions/node_modules
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
    ports:
      # See firebase.json
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3003:3003
      - 3004:3004
    networks:
      - net
  nginx:
    image: nginx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - net

volumes:
  db:

networks:
  net:
