#!/bin/bash

# Not setting this because firebase complains since we're not authenticated
# set -e -o pipefail

FUNCTIONS_DIR="$FIREBASE_DIR/functions"
CONFIG_PATH="$FIREBASE_DIR/firebase.json"
# https://firebase.google.com/docs/emulator-suite/connect_firestore#choose_a_firebase_project
DEMO="demo-code-buddy-development"

cd "$FUNCTIONS_DIR" && pnpm dev
firebase emulators:start --project "$DEMO" --import="$DATA_DIR" --export-on-exit --config "$CONFIG_PATH"


