// Generated by wxt
export {};
declare global {
  const ContentScriptContext: (typeof import("wxt/utils/content-script-context"))["ContentScriptContext"];
  const DEBOUNCE_DELAY_MS: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/usePaginate"))["DEBOUNCE_DELAY_MS"];
  const InvalidMatchPattern: (typeof import("wxt/utils/match-patterns"))["InvalidMatchPattern"];
  const MatchPattern: (typeof import("wxt/utils/match-patterns"))["MatchPattern"];
  const REFRESH_INTERVAL_MS: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/usePaginate"))["REFRESH_INTERVAL_MS"];
  const appendClassIdempotent: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/dom"))["appendClassIdempotent"];
  const assertUnreachable: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/error"))["assertUnreachable"];
  const browser: (typeof import("wxt/browser"))["browser"];
  const calculateNewRTT: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/heartbeat"))["calculateNewRTT"];
  const capitalize: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/string"))["capitalize"];
  const cn: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/cn"))["cn"];
  const codeViewable: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/model"))["codeViewable"];
  const constructUrlFromQuestionId: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/url"))["constructUrlFromQuestionId"];
  const createIframeUi: (typeof import("wxt/utils/content-script-ui/iframe"))["createIframeUi"];
  const createIntegratedUi: (typeof import("wxt/utils/content-script-ui/integrated"))["createIntegratedUi"];
  const createShadowRootUi: (typeof import("wxt/utils/content-script-ui/shadow-root"))["createShadowRootUi"];
  const defaultTo: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/cast"))["defaultTo"];
  const defineAppConfig: (typeof import("wxt/utils/define-app-config"))["defineAppConfig"];
  const defineBackground: (typeof import("wxt/utils/define-background"))["defineBackground"];
  const defineContentScript: (typeof import("wxt/utils/define-content-script"))["defineContentScript"];
  const defineUnlistedScript: (typeof import("wxt/utils/define-unlisted-script"))["defineUnlistedScript"];
  const defineWxtPlugin: (typeof import("wxt/utils/define-wxt-plugin"))["defineWxtPlugin"];
  const disablePointerEvents: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/dom"))["disablePointerEvents"];
  const fakeBrowser: (typeof import("wxt/testing"))["fakeBrowser"];
  const formatTime: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/heartbeat"))["formatTime"];
  const generateId: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/dom"))["generateId"];
  const getQuestionIdFromUrl: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/url"))["getQuestionIdFromUrl"];
  const getSessionId: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/url"))["getSessionId"];
  const getUnixTs: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/heartbeat"))["getUnixTs"];
  const hideToRoot: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/dom"))["hideToRoot"];
  const identity: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/cast"))["identity"];
  const injectScript: (typeof import("wxt/utils/inject-script"))["injectScript"];
  const isString: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/validation"))["isString"];
  const isValidEmail: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/validation"))["isValidEmail"];
  const poll: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/poll"))["poll"];
  const promisedIdentity: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/cast"))["promisedIdentity"];
  const storage: (typeof import("wxt/utils/storage"))["storage"];
  const timeAgo: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/heartbeat"))["timeAgo"];
  const useAppConfig: (typeof import("wxt/utils/app-config"))["useAppConfig"];
  const useAppState: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/index"))["useAppState"];
  const useAuthenticate: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useAuthenticate"))["default"];
  const useDevReload: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useDevReload"))["default"];
  const useDevSetupRoom: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useDevSetupRoom"))["default"];
  const useFirebaseListener: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useFirebaseListener"))["useFirebaseListener"];
  const useInferTests: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useInferTests"))["default"];
  const useLanguageExtension: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useLanguageExtension"))["default"];
  const useOnMount: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useOnMount"))["useOnMount"];
  const usePaginate: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/usePaginate"))["default"];
  const usePeerSelection: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/index"))["usePeerSelection"];
  const useRTC: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/index"))["useRTC"];
  const useResource: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useResource"))["default"];
  const useSelectedQuestions: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useSelectedQuestions"))["useSelectedQuestions"];
  const useSession: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/hooks/index"))["useSession"];
  const wait: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/poll"))["wait"];
  const waitForElement: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/dom"))["waitForElement"];
  const withPayload: (typeof import("/Users/nickbar01234/projects/codebuddy/extension/src/utils/messages"))["withPayload"];
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from "wxt/browser";
  // @ts-ignore
  export type { WxtWindowEventMap } from "wxt/utils/content-script-context";
  // @ts-ignore
  export type {
    IframeContentScriptUi,
    IframeContentScriptUiOptions,
  } from "wxt/utils/content-script-ui/iframe";
  // @ts-ignore
  export type {
    IntegratedContentScriptUi,
    IntegratedContentScriptUiOptions,
  } from "wxt/utils/content-script-ui/integrated";
  // @ts-ignore
  export type {
    ShadowRootContentScriptUi,
    ShadowRootContentScriptUiOptions,
  } from "wxt/utils/content-script-ui/shadow-root";
  // @ts-ignore
  export type {
    AutoMount,
    AutoMountOptions,
    ContentScriptAnchoredOptions,
    ContentScriptAppendMode,
    ContentScriptInlinePositioningOptions,
    ContentScriptModalPositioningOptions,
    ContentScriptOverlayAlignment,
    ContentScriptOverlayPositioningOptions,
    ContentScriptPositioningOptions,
    ContentScriptUi,
    ContentScriptUiOptions,
    StopAutoMount,
  } from "wxt/utils/content-script-ui/types";
  // @ts-ignore
  export type { WxtAppConfig } from "wxt/utils/define-app-config";
  // @ts-ignore
  export type {
    InjectScriptOptions,
    ScriptPublicPath,
  } from "wxt/utils/inject-script";
  // @ts-ignore
  export type {
    MigrationError,
    StorageArea,
    StorageAreaChanges,
    StorageItemKey,
    WxtStorage,
    WxtStorageItem,
  } from "wxt/utils/storage";
  // @ts-ignore
  export type { UseFirebaseListenerProps } from "/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useFirebaseListener";
  // @ts-ignore
  export type { Resource } from "/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useResource";
  import("wxt/browser");
  import("wxt/utils/storage");
  import("wxt/utils/content-script-context");
  import("wxt/utils/content-script-ui/iframe");
  import("wxt/utils/content-script-ui/integrated");
  import("wxt/utils/content-script-ui/shadow-root");
  import("wxt/utils/content-script-ui/types");
  import("wxt/utils/define-app-config");
  import("wxt/utils/inject-script");
  import(
    "/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useFirebaseListener"
  );
  import(
    "/Users/nickbar01234/projects/codebuddy/extension/src/hooks/useResource"
  );
}
