import { RoomWithSession } from "./PublicRoomTable";

export const sampleRooms: RoomWithSession[] = [
  {
    id: "1",
    name: "CodeMasters",
    currentProblem: "3. Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    users: 4,
    timeElapsed: 1200,
  },
  {
    id: "2",
    name: "AlgoWarriors",
    currentProblem: "1. Two Sum",
    difficulty: "Easy",
    users: 6,
    timeElapsed: 800,
  },
  {
    id: "3",
    name: "HardcoreHackers",
    currentProblem:
      "1420. Build Array Where You Can Find The Maximum Exactly K Comparisons",
    difficulty: "Hard",
    users: 3,
    timeElapsed: 3600,
  },
  {
    id: "4",
    name: "LeetLegends",
    currentProblem: "5. Longest Palindromic Substring",
    difficulty: "Medium",
    users: 5,
    timeElapsed: 1500,
  },
  {
    id: "5",
    name: "BinaryBeasts",
    currentProblem: "2. Add Two Numbers",
    difficulty: "Easy",
    users: 2,
    timeElapsed: 600,
  },
  {
    id: "6",
    name: "DynamicCoders",
    currentProblem: "10. Regular Expression Matching",
    difficulty: "Hard",
    users: 4,
    timeElapsed: 2400,
  },
  {
    id: "7",
    name: "StackOverflowers",
    currentProblem: "20. Valid Parentheses",
    difficulty: "Easy",
    users: 7,
    timeElapsed: 900,
  },
  {
    id: "8",
    name: "RecursionNinjas",
    currentProblem: "22. Generate Parentheses",
    difficulty: "Medium",
    users: 3,
    timeElapsed: 1800,
  },
  {
    id: "9",
    name: "GraphGurus",
    currentProblem: "133. Clone Graph",
    difficulty: "Medium",
    users: 5,
    timeElapsed: 2100,
  },
  {
    id: "10",
    name: "ArrayAvengers",
    currentProblem: "53. Maximum Subarray",
    difficulty: "Easy",
    users: 6,
    timeElapsed: 700,
  },
  {
    id: "11",
    name: "HashMapHeroes",
    currentProblem: "49. Group Anagrams",
    difficulty: "Medium",
    users: 4,
    timeElapsed: 1600,
  },
  {
    id: "12",
    name: "TreeTraversers",
    currentProblem: "104. Maximum Depth of Binary Tree",
    difficulty: "Easy",
    users: 3,
    timeElapsed: 500,
  },
  {
    id: "13",
    name: "SortingSamurais",
    currentProblem: "75. Sort Colors",
    difficulty: "Medium",
    users: 2,
    timeElapsed: 1400,
  },
  {
    id: "14",
    name: "DPWizards",
    currentProblem: "70. Climbing Stairs",
    difficulty: "Easy",
    users: 8,
    timeElapsed: 600,
  },
  {
    id: "15",
    name: "BitManipulators",
    currentProblem: "136. Single Number",
    difficulty: "Easy",
    users: 5,
    timeElapsed: 400,
  },
  {
    id: "16",
    name: "MatrixMasters",
    currentProblem: "48. Rotate Image",
    difficulty: "Medium",
    users: 4,
    timeElapsed: 1200,
  },
  {
    id: "17",
    name: "QueueKings",
    currentProblem: "225. Implement Stack using Queues",
    difficulty: "Easy",
    users: 3,
    timeElapsed: 800,
  },
  {
    id: "18",
    name: "TrieTitans",
    currentProblem: "208. Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    users: 5,
    timeElapsed: 1500,
  },
  {
    id: "19",
    name: "GreedyGang",
    currentProblem: "55. Jump Game",
    difficulty: "Medium",
    users: 6,
    timeElapsed: 1800,
  },
  {
    id: "20",
    name: "SlidingWindowWizards",
    currentProblem: "239. Sliding Window Maximum",
    difficulty: "Hard",
    users: 2,
    timeElapsed: 2400,
  },
  {
    id: "21",
    name: "BinarySearchSquad",
    currentProblem: "704. Binary Search",
    difficulty: "Easy",
    users: 7,
    timeElapsed: 900,
  },
  {
    id: "22",
    name: "HeapHeroes",
    currentProblem: "215. Kth Largest Element in an Array",
    difficulty: "Medium",
    users: 4,
    timeElapsed: 2000,
  },
  {
    id: "23",
    name: "GraphExplorers",
    currentProblem: "207. Course Schedule",
    difficulty: "Medium",
    users: 5,
    timeElapsed: 2100,
  },
  {
    id: "24",
    name: "BacktrackingBosses",
    currentProblem: "79. Word Search",
    difficulty: "Medium",
    users: 3,
    timeElapsed: 1700,
  },
  {
    id: "25",
    name: "DivideAndConquerors",
    currentProblem: "169. Majority Element",
    difficulty: "Easy",
    users: 6,
    timeElapsed: 700,
  },
  {
    id: "26",
    name: "KnapsackKnights",
    currentProblem: "416. Partition Equal Subset Sum",
    difficulty: "Medium",
    users: 4,
    timeElapsed: 1600,
  },
  {
    id: "27",
    name: "BitwiseBandits",
    currentProblem: "338. Counting Bits",
    difficulty: "Easy",
    users: 5,
    timeElapsed: 800,
  },
  {
    id: "28",
    name: "FloodFillFanatics",
    currentProblem: "733. Flood Fill",
    difficulty: "Easy",
    users: 3,
    timeElapsed: 600,
  },
  {
    id: "29",
    name: "PermutationPros",
    currentProblem: "46. Permutations",
    difficulty: "Medium",
    users: 4,
    timeElapsed: 1400,
  },
  {
    id: "30",
    name: "SubsetSpecialists",
    currentProblem: "78. Subsets",
    difficulty: "Medium",
    users: 5,
    timeElapsed: 1300,
  },
];
