import { Room } from "./JoinRoomPanel";

export const sampleRooms: Room[] = [
  {
    id: "1",
    name: "CodeMasters",
    currentProblem: "3. Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    users: 4,
    timeElapsed: 1200,
  },
  {
    id: "2",
    name: "AlgoWarriors",
    currentProblem: "1. Two Sum",
    difficulty: "Easy",
    users: 6,
    timeElapsed: 800,
  },
  {
    id: "3",
    name: "HardcoreHackers",
    currentProblem:
      "1420. Build Array Where You Can Find The Maximum Exactly K Comparisons",
    difficulty: "Hard",
    users: 3,
    timeElapsed: 3600,
  },
  {
    id: "4",
    name: "LeetLegends",
    currentProblem: "5. Longest Palindromic Substring",
    difficulty: "Medium",
    users: 5,
    timeElapsed: 1500,
  },
  {
    id: "5",
    name: "BinaryBeasts",
    currentProblem: "2. Add Two Numbers",
    difficulty: "Easy",
    users: 2,
    timeElapsed: 600,
  },
  {
    id: "6",
    name: "DynamicCoders",
    currentProblem: "10. Regular Expression Matching",
    difficulty: "Hard",
    users: 4,
    timeElapsed: 2400,
  },
  {
    id: "7",
    name: "StackOverflowers",
    currentProblem: "20. Valid Parentheses",
    difficulty: "Easy",
    users: 7,
    timeElapsed: 900,
  },
  {
    id: "8",
    name: "RecursionNinjas",
    currentProblem: "22. Generate Parentheses",
    difficulty: "Medium",
    users: 3,
    timeElapsed: 1800,
  },
  {
    id: "9",
    name: "GraphGurus",
    currentProblem: "133. Clone Graph",
    difficulty: "Medium",
    users: 5,
    timeElapsed: 2100,
  },
  {
    id: "10",
    name: "ArrayAvengers",
    currentProblem: "53. Maximum Subarray",
    difficulty: "Easy",
    users: 6,
    timeElapsed: 700,
  },
  {
    id: "11",
    name: "HashMapHeroes",
    currentProblem: "49. Group Anagrams",
    difficulty: "Medium",
    users: 4,
    timeElapsed: 1600,
  },
  {
    id: "12",
    name: "TreeTraversers",
    currentProblem: "104. Maximum Depth of Binary Tree",
    difficulty: "Easy",
    users: 3,
    timeElapsed: 500,
  },
  {
    id: "13",
    name: "SortingSamurais",
    currentProblem: "75. Sort Colors",
    difficulty: "Medium",
    users: 2,
    timeElapsed: 1400,
  },
  {
    id: "14",
    name: "DPWizards",
    currentProblem: "70. Climbing Stairs",
    difficulty: "Easy",
    users: 8,
    timeElapsed: 600,
  },
  {
    id: "15",
    name: "BitManipulators",
    currentProblem: "136. Single Number",
    difficulty: "Easy",
    users: 5,
    timeElapsed: 400,
  },
];
