name: Install
description: Install node and pnpm
runs:
  using: "composite"
  steps:
    - name: "Install pnpm"
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: "Setup node"
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    - name: pnpm
      shell: bash
      working-directory: ${{ github.workspace }}
      run: pnpm install --frozen-lockfile
