name: Tests

on:
  push:
    branches: ["na/firebase-security"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.x"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Start Firebase emulator 
        run: docker compose up -d
      - name: Wait for firebase emulator
        run: | 
          echo "Waiting for firebase emulator"
          for i in {1...20}; do
            curl -s http:localhost:3001 && break
            echo "Waiting..."
            sleep 2
          done 
      - name: Run tests
        run: pnpm test
