name: Tests

on:
  push: 
    branches: ["na/firebase-security"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["22.x"]
    
    services:
      firebase-emulator: 
        build:
        # build the container from current directory
          context: . 
          dockerfile: Dockerfile
        ports:
          - 3001:3001
        #make sure that the docker is running before ci/cd
        options: |
          --health-cmd "curl --fail http://localhost:3001 || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm i
      - name: Run tests
        run: pnpm test
